install.packages("cluster",repos='http://cran.us.r-project.org')
install.packages("fpc",repos='http://cran.us.r-project.org')
install.packages("seqinr",repos='http://cran.us.r-project.org')
source("http://bioconductor.org/biocLite.R")
biocLite()